// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using visa_consulatant.Data;

#nullable disable

namespace visa_consulatant.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250803123343_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("visa_consulatant.Models.CarouselImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<int>("ImageUploadId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ImageUploadId");

                    b.ToTable("CarouselImages");
                });

            modelBuilder.Entity("visa_consulatant.Models.ContactInquiry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Subject")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("VisaType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("ContactInquiries");
                });

            modelBuilder.Entity("visa_consulatant.Models.HomePageContent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BannerImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HeroImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ServicesOverview")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WelcomeMessage")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("HomePageContents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Your trusted partner for all Australian immigration services. We provide expert guidance and support for your visa applications to Australia.",
                            LastUpdated = new DateTime(2025, 8, 3, 12, 33, 41, 22, DateTimeKind.Utc).AddTicks(2375),
                            ServicesOverview = "We offer comprehensive Australian immigration services including skilled migration, student visas, partner visas, tourist visas, and permanent residency applications.",
                            Title = "Guru Kirpa Immigration - Your Gateway to Australia",
                            UpdatedBy = "System",
                            WelcomeMessage = "Welcome to Guru Kirpa Immigration - Your Gateway to Australia"
                        });
                });

            modelBuilder.Entity("visa_consulatant.Models.ImageUpload", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<byte[]>("ImageData")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("ImageType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UploadedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ImageUploads");
                });

            modelBuilder.Entity("visa_consulatant.Models.Offer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("DiscountPercentage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int?>("ImageUploadId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("ValidFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ValidUntil")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ImageUploadId");

                    b.ToTable("Offers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 8, 3, 12, 33, 41, 24, DateTimeKind.Utc).AddTicks(8384),
                            CreatedBy = "System",
                            Description = "Get 20% off on student visa processing fees. Limited time offer for new students!",
                            DiscountPercentage = 20.00m,
                            IsActive = true,
                            Title = "Student Visa Special Offer",
                            ValidFrom = new DateTime(2025, 8, 3, 12, 33, 41, 24, DateTimeKind.Utc).AddTicks(4601),
                            ValidUntil = new DateTime(2025, 11, 3, 12, 33, 41, 24, DateTimeKind.Utc).AddTicks(5973)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 8, 3, 12, 33, 41, 25, DateTimeKind.Utc).AddTicks(554),
                            CreatedBy = "System",
                            Description = "Complete family immigration package with special rates for families of 3 or more members.",
                            DiscountPercentage = 15.00m,
                            IsActive = true,
                            Title = "Family Package Deal",
                            ValidFrom = new DateTime(2025, 8, 3, 12, 33, 41, 25, DateTimeKind.Utc).AddTicks(527),
                            ValidUntil = new DateTime(2026, 2, 3, 12, 33, 41, 25, DateTimeKind.Utc).AddTicks(529)
                        });
                });

            modelBuilder.Entity("visa_consulatant.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 8, 3, 12, 33, 41, 16, DateTimeKind.Utc).AddTicks(8001),
                            Email = "admin@gurukirpa.com",
                            IsActive = true,
                            PasswordHash = "$2a$11$am8zvlm8es8A0tsF70NdPuysIEZ.EDyhqN6i8A3Rl4Pmqu6PqSTmS",
                            Role = "Admin",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("visa_consulatant.Models.VisaService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProcessingTime")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("VisaServices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "Australia",
                            CreatedAt = new DateTime(2025, 8, 3, 12, 33, 41, 23, DateTimeKind.Utc).AddTicks(4420),
                            Description = "Professional skilled migration services for qualified workers seeking permanent residency in Australia through points-based system.",
                            IsActive = true,
                            Name = "Skilled Migration Visa",
                            ProcessingTime = "6-12 months"
                        },
                        new
                        {
                            Id = 2,
                            Country = "Australia",
                            CreatedAt = new DateTime(2025, 8, 3, 12, 33, 41, 23, DateTimeKind.Utc).AddTicks(5567),
                            Description = "Comprehensive student visa services for international students wishing to study at Australian educational institutions.",
                            IsActive = true,
                            Name = "Student Visa (Subclass 500)",
                            ProcessingTime = "1-3 months"
                        },
                        new
                        {
                            Id = 3,
                            Country = "Australia",
                            CreatedAt = new DateTime(2025, 8, 3, 12, 33, 41, 23, DateTimeKind.Utc).AddTicks(5572),
                            Description = "Expert guidance for partner visa applications including spouse, de facto, and prospective marriage visas.",
                            IsActive = true,
                            Name = "Partner Visa",
                            ProcessingTime = "12-24 months"
                        },
                        new
                        {
                            Id = 4,
                            Country = "Australia",
                            CreatedAt = new DateTime(2025, 8, 3, 12, 33, 41, 23, DateTimeKind.Utc).AddTicks(5577),
                            Description = "Tourist and visitor visa services for short-term stays in Australia for tourism, business, or family visits.",
                            IsActive = true,
                            Name = "Tourist Visa (Subclass 600)",
                            ProcessingTime = "2-4 weeks"
                        },
                        new
                        {
                            Id = 5,
                            Country = "Australia",
                            CreatedAt = new DateTime(2025, 8, 3, 12, 33, 41, 23, DateTimeKind.Utc).AddTicks(5582),
                            Description = "Temporary skill shortage visa services for skilled workers sponsored by Australian employers.",
                            IsActive = true,
                            Name = "Work Visa (Subclass 482)",
                            ProcessingTime = "3-6 months"
                        },
                        new
                        {
                            Id = 6,
                            Country = "Australia",
                            CreatedAt = new DateTime(2025, 8, 3, 12, 33, 41, 23, DateTimeKind.Utc).AddTicks(5586),
                            Description = "Business and investment visa services for entrepreneurs and investors seeking to establish businesses in Australia.",
                            IsActive = true,
                            Name = "Business Innovation Visa",
                            ProcessingTime = "12-18 months"
                        });
                });

            modelBuilder.Entity("visa_consulatant.Models.CarouselImage", b =>
                {
                    b.HasOne("visa_consulatant.Models.ImageUpload", "ImageUpload")
                        .WithMany()
                        .HasForeignKey("ImageUploadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImageUpload");
                });

            modelBuilder.Entity("visa_consulatant.Models.Offer", b =>
                {
                    b.HasOne("visa_consulatant.Models.ImageUpload", "ImageUpload")
                        .WithMany()
                        .HasForeignKey("ImageUploadId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ImageUpload");
                });
#pragma warning restore 612, 618
        }
    }
}
